default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  database: database_portfolio
  pool: <%= ENV['RAILS_MAX_THREADS'] || 5 %>
  timeout: 5000

development:
  <<: *default


test:
  <<: *default
#  database: db/test.sqlite3

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  master_key: <%= ENV['RAILS_MASTER_KEY'] %>